sudo: required
addons:
  ssh_known_hosts: beech.bjrm.de:222
services:
- docker
script:
- make setup generate
before_install:
- openssl aes-256-cbc -K $encrypted_413cef53488e_key -iv $encrypted_413cef53488e_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -e "ssh -p 222" $TRAVIS_BUILD_DIR/public/ deploy_gartenwohnung@beech.bjrm.de:/opt/web_static/gartenwohnung-muensterland.de/
  on:
    branch: master
